Fix Android Service being inconsistent between runs
jfversluis/Plugin.Maui.ScreenRecording pull request #21
Opened 2024-12-28 05:38 UTC by mr5z

Changes are only for Android:
- Fix Android Service inconsistency, i.e., sometimes it's running, sometimes it isn't.
- Code refactors to achieve the fix, plus added some screen recording tweaks.
- Update Notification icon (maybe this is unnecessary)

2024-12-29 20:00 UTC, jfversluis commented
Whoop this is amazing, thank you so much! I'll look at it asap :)

2025-01-04 18:30 UTC, jfversluis requested changes
Unfortunately when I try to start a recording on Android 31 on an emulator

```
java.lang.NoSuchMethodError: no non-static method "Landroid/content/Intent;.getParcelableExtra(Ljava/lang/String;Ljava/lang/Class;)Ljava/lang/Object;"
at Java.Interop.JniEnvironment.InstanceMethods.GetMethodID(JniObjectReference type, String name, String signature) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/net7.0/JniEnvironment.g.cs:line 19947
   at Java.Interop.JniType.GetInstanceMethod(String name, String signature) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniType.cs:line 250
   at Java.Interop.JniPeerMembers.JniInstanceMethods.GetMethodInfo(String method, String signature) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods.cs:line 126
   at Java.Interop.JniPeerMembers.JniInstanceMethods.GetMethodInfo(String encodedMember) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods.cs:line 93
   at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualObjectMethod(String encodedMember, IJavaPeerable self, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:line 863
   at Android.Content.Intent.GetParcelableExtra(String name, Class clazz) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Android.Content.Intent.cs:line 3442
   at Plugin.Maui.ScreenRecording.ScreenRecordingService.GetParcelableExtra[Messenger](Intent intent, String name) in /Users/jfversluis/Documents/GitHub/Plugin.Maui.ScreenRecording/src/Plugin.Maui.ScreenRecording/ScreenRecordingService.android.cs:line 135
   at Plugin.Maui.ScreenRecording.ScreenRecordingService.NotifyHandler(Intent intent) in /Users/jfversluis/Documents/GitHub/Plugin.Maui.ScreenRecording/src/Plugin.Maui.ScreenRecording/ScreenRecordingService.android.cs:line 63
   at Plugin.Maui.ScreenRecording.ScreenRecordingService.OnStartCommand(Intent intent, StartCommandFlags flags, Int32 startId) in /Users/jfversluis/Documents/GitHub/Plugin.Maui.ScreenRecording/src/Plugin.Maui.ScreenRecording/ScreenRecordingService.android.cs:line 29
   at Android.App.Service.n_OnStartCommand_Landroid_content_Intent_II(IntPtr jnienv, IntPtr native__this, IntPtr native_intent, Int32 native_flags, Int32 startId) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Android.App.Service.cs:line 409
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLII_I(_JniMarshal_PPLII_I callback, IntPtr jnienv, IntPtr klazz, IntPtr p0, Int32 p1, Int32 p2) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 275
  --- End of managed Java.Lang.NoSuchMethodError stack trace ---
java.lang.NoSuchMethodError: no non-static method "Landroid/content/Intent;.getParcelableExtra(Ljava/lang/String;Ljava/lang/Class;)Ljava/lang/Object;"
	at crc64347e7888d3fc1c32.ScreenRecordingService.n_onStartCommand(Native Method)
	at crc64347e7888d3fc1c32.ScreenRecordingService.onStartCommand(ScreenRecordingService.java:39)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4639)
	at android.app.ActivityThread.access$2000(ActivityThread.java:247)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2091)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

2025-01-04 18:53 UTC, jfversluis commented on src/Plugin.Maui.ScreenRecording/ScreenRecordingService.android.cs
> +            : intent?.GetParcelableExtra(name, Java.Lang.Class.FromType(typeof(T))) as T;
```suggestion
        OperatingSystem.IsAndroidVersionAtLeast(33)
            ? intent?.GetParcelableExtra(name, Java.Lang.Class.FromType(typeof(T))) as T
            :  intent?.GetParcelableExtra(name) as T;
```

I think the OS version check is wrong, if I swap the functions around here it does work.

2025-01-04 19:06 UTC, jfversluis commented on src/Plugin.Maui.ScreenRecording/ScreenRecordingService.android.cs
> +            // TODO ugly fix
Is this still a TODO? 😅

2025-01-05 05:25 UTC, mr5z commented on src/Plugin.Maui.ScreenRecording/ScreenRecordingService.android.cs
> +            // TODO ugly fix
Yeah I think this is hackish way to do it. I was thinking of using Android's Handler to send messages from the Service.

2025-01-05 05:26 UTC, mr5z commented on src/Plugin.Maui.ScreenRecording/ScreenRecordingService.android.cs
> +            : intent?.GetParcelableExtra(name, Java.Lang.Class.FromType(typeof(T))) as T;
Oops 😅

2025-01-05 08:10 UTC, jfversluis commented on src/Plugin.Maui.ScreenRecording/ScreenRecordingService.android.cs
> +            // TODO ugly fix
So will you still change that now or whats the plan?

2025-01-05 08:16 UTC, mr5z commented on src/Plugin.Maui.ScreenRecording/ScreenRecordingService.android.cs
> +            // TODO ugly fix
Unfortunately, I don't think I can update it anytime soon as I'll be very busy this week onwards. Maybe we can proceed with that for the meantime?

2025-01-05 09:03 UTC, jfversluis approved these changes

2025-01-05 09:03 UTC, merged